### ISSUE TITLE
Extra fraction in the result of in_each_component method

### ISSUE THREAD

**Issue by wbotelhos** [tmlee/time_difference#13]
Given:

```ruby
time = Time.now
TimeDifference.between(time, time + 6.months).in_each_component
```

Then:

```ruby
{
  :years   => 0.5,
  :months  => 6.02,
  :weeks   => 26.14,
  :days    => 183.0,
  :hours   => 4392.0,
  :minutes => 263520.0,
  :seconds => 15811200.0
}
```

The `months` has `0.02` more, why this difference, not just `6.0`?

**Comment by tmlee** [comment]
@wbotelhos computer calculates at a higher precision http://www.wolframalpha.com/input/?i=Time+from+now+and+6+months+later

**Comment by wbotelhos** [comment]
Hi, Thanks for the answer.

I had to calculate manually using ` next_month` and counting the index, because we have months with 28, 29, 30 and 31 days. In a big range of months we get a big difference of amount/month. 6 months * 1 dollar is different of 6.02 months vs 1 dollar. But it works fine for weeks, days and so...

Thank you.
