### ISSUE TITLE
NoMethodError for humanize

### ISSUE THREAD

**Issue by thrgamon** [tmlee/time_difference#23]
Hey,

Tried to do this within a rails 4 project.

time_difference = TimeDifference.between(Time.now, departure_time).humanize

But returned with this:

NoMethodError (undefined method `humanize' for #<TimeDifference:0x007fa4a59cbf48 @time_diff=14140786.331287146>):

The gem seems to be working fine otherwise.

I am using ruby 2.3

Tom

**Comment by tmlee** [comment]
@thrgamon I published a new build at rubygems https://rubygems.org/gems/time_difference
Give that a go, otherwise try installing from the master branch first if it does not work.
