### ISSUE TITLE
Wrong year reported

### ISSUE THREAD

**Issue by pmontrasio** [tmlee/time_difference#3]
The number of years between a date and the same date the year before plus one day should be 0 but it's reported as 1.

    require "rubygems"
    require "time_difference"
 
    d1 = Date.new(2014, 1, 20)
    d2 = Date.new(2013, 1, 20)
    td2 = TimeDifference.between(d1.to_time, d2.to_time) # expected 1 year
 
    d3 = Date.new(2013, 1, 19)
    td3 = TimeDifference.between(d1.to_time, d3.to_time) # expected 1 year
 
    d4 = Date.new(2013, 1, 21)
    td4 = TimeDifference.between(d1.to_time, d4.to_time) # expected 0 years
 
    p td2.in_years == 1.0
    p td3.in_years == 1.0
    p td4.in_years == 0.0
  
    p td4.in_each_component

Output

    true
    true
    false
    {:years=>1.0, :months=>11.97, :weeks=>52.0, :days=>364.0, :hours=>8736.0, :minutes=>524160.0, :seconds=>31449600.0}

years == 1.0 and days == 364.0 seem contradictory.

**Comment by Argorate** [comment]
simply add : 

elsif time_component == :years
          diff = @time_diff / 31536000.0 #(365 * 24 * 60 * 60)

instead of * 1.year (= 365.25 day)

**Comment by tmlee** [comment]
It can be quite difficult to depend on 365 days being 1 year for this case
https://www.wolframalpha.com/input/?i=2013%2F1%2F21+to+2014%2F1%2F20

**Comment by pmontrasio** [comment]
More than one year passed since I opened this issue. I had to compute the age of a person and this is how I solved it.

    def age(birth_date, now)
      return 0 if birth_date >= now
      years = now.year - birth_date.year
      if now.month < birth_date.month
        years -= 1
      elsif now.month == birth_date.month
        if now.day < birth_date.day
          years -= 1
        end
      end
      years
    end

Run ```irb```,  copy that code into it and

    2.2.1 :013 > require "date"
     => true 
    2.2.1 :014 > age(Date.new(2013, 1, 21), Date.new(2014, 1, 20))
     => 0 
    2.2.1 :015 > age(Date.new(2013, 1, 20), Date.new(2014, 1, 20))
     => 1 

This is a much less general case than what time_difference has to do but maybe it can hint to a way to fix it.

**Comment by tmlee** [comment]
If there is a need to implement custom calculations like what you, @crazyjin, and @Argorate suggested, would prefer to have it as a separate configuration. Would still like to have the time calculation result to match what Wolfram Alpha is returning.
