### ISSUE TITLE
time diff wrong calculation?

### ISSUE THREAD

**Issue by mtricolici** [tmlee/time_difference#32]
```
# cat test.rb 
#!/usr/bin/env ruby
require 'date'
require 'time_difference'

now = Time.now.utc
puts "now is #{now}"

backup_date = DateTime.strptime('2017-06-28-000001', '%Y-%m-%d-%H%M%S').utc
puts "backup_date is #{backup_date}"

h = TimeDifference.between(backup_date, now).in_hours
puts "...time diff in hours=#{h}"
```

```
# ./test.rb 
now is 2017-06-28 07:54:20 UTC
backup_date is 2017-06-28 00:00:01 UTC
...time diff in hours=102454424.73
```

```
# ruby -v
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux-musl]
time_difference (0.5.0)
```

**Comment by mtricolici** [comment]
another test

```
ruby 2.3.3p222
time_difference (0.5.0)

#!/usr/bin/env ruby
require 'date'
require 'time_difference'

now = DateTime.now.utc
puts "now is #{now}. class=#{now.class}"

backup_date = DateTime.strptime('2017-06-28-000001', '%Y-%m-%d-%H%M%S').utc
puts "backup_date is #{backup_date}. class=#{backup_date.class}"

h = TimeDifference.between(backup_date, now).in_hours
puts "...time diff in hours=#{h}"



now is 2017-06-28 08:26:35 UTC. class=Time
backup_date is 2017-06-28 00:00:01 UTC. class=Time
...time diff in hours=109421732.92
```

**Comment by mtricolici** [comment]
works fine in ruby 2.2.* and 2.4.* (issue apperas in 2.3.1 & 2.3.4)

**Comment by bodsch** [comment]
the same here
```
/ # ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux-musl]

/ # gem list time_difference

*** LOCAL GEMS ***

time_difference (0.5.0)

irb(main):024:0* now = DateTime.now.utc
=> 2017-06-29 13:56:31 UTC
irb(main):025:0> last = Time.at( 1498521600000 / 1000 )
=> 2017-06-27 00:00:00 +0000
irb(main):026:0> puts "now is #{now}. class=#{now.class}"
now is 2017-06-29 13:56:31 UTC. class=Time
=> nil
irb(main):027:0> puts "last is #{last}. class=#{last.class}"
last is 2017-06-27 00:00:00 +0000. class=Time
=> nil
irb(main):028:0> h = TimeDifference.between(last,now).in_each_component
=> {:years=>7036934032103.32, :months=>633348816.38, :weeks=>134865296959.48, :days=>19266470994.21, :hours=>802769624.76, :minutes=>13379493.75, :seconds=>222991.56243300438}
```

**Comment by BLauris** [comment]
I got this issue on all of these ruby versions `2.3.1`, `2.3.3`, `2.3.4` and `2.4.1`.

**Comment by aviflax** [comment]
I just encountered this problem as well, but in my case it doesn’t appear to have anything to do with the runtime version. Rather, I encountered the problem while upgrading dependencies. I managed to narrow it down to ActiveSupport. For whatever reason, when I use ActiveSupport 5.1.1 it works fine, but when I use 5.1.2 it breaks. I checked [the release notes for 5.1.2](https://github.com/rails/rails/blob/v5.1.2/activesupport/CHANGELOG.md#rails-512-june-26-2017) and they only describe two changes. One of them, however, is “Fix implicit coercion calculations with scalars and durations” — so that might be the culprit.

I have not dug further than that, because personally I’d rather just stick with 5.1.1 for now rather than take more time to debug this.

HTH!

**Comment by aviflax** [comment]
Oh and also I noticed that #31 _might_ address this. Not entirely sure.

**Comment by fadynaffa3** [comment]
Any update? @aviflax your 100% right the issue happened when I updated rails to 5.1.2 as 5.1.1 had no problems.

**Comment by Jacotb** [comment]
Can confirm. Rails 5.1.2 changed the behaviour of `x / 1.hour`. It now returns `x.hours` rather than `(x/3600).hours`.

```
2.4.0 :033 > TimeDifference.between(DateTime.now, DateTime.now - 1.week).in_seconds
 => 604799.9996852875 
2.4.0 :034 > TimeDifference.between(DateTime.now, DateTime.now - 1.week).in_hours
 => 2177279998.97 
```

**Comment by fadynaffa3** [comment]
You can find the change here https://github.com/rails/rails/blob/v5.1.2/activesupport/CHANGELOG.md

**Comment by conroywhitney** [comment]
Thank you! This helped me troubleshoot the issue much quicker than I could have on my own.

BTW, [activesupport v5.1.3](https://rubygems.org/gems/activesupport/versions/5.1.3) is out now and fixes this issue. `bundle update rails` should do the trick.

**Comment by tmlee** [comment]
Thanks guys. Verifying that the library continues to work as expected with the latest version of ActiveSupport. Will re-open if anyone is still facing issues for this one
