### ISSUE TITLE
in_component broken on Rails 5.1.2

### ISSUE THREAD

**Issue by Jacotb** [tmlee/time_difference#34]
Rails 5.1.2 changed the behaviour of x / 1.hour. It now returns x.hours rather than (x/3600).hours.

Example:
```
2.4.0 :033 > TimeDifference.between(DateTime.now, DateTime.now - 1.week).in_seconds
 => 604799.9996852875 
2.4.0 :034 > TimeDifference.between(DateTime.now, DateTime.now - 1.week).in_hours
 => 2177279998.97 
```

Proposed fix in time_difference.rb:93..95:
```
  def in_component(component)
    (@time_diff.seconds / 1.send(component)).round(2)
  end
```

**Comment by conroywhitney** [comment]
This seems like it might have been an issue in `rails`. [activesupport v5.1.3](https://rubygems.org/gems/activesupport/versions/5.1.3) is out now and fixes this issue. Running `bundle update rails` should do the trick.

**Comment by tmlee** [comment]
Same for https://github.com/tmlee/time_difference/issues/32. Verifying that this works with the latest version of activesupport. Reopening the issue if you are still seeing some problems.
