### ISSUE TITLE
Incorrect results for dates way in the future

### ISSUE THREAD

**Issue by mlt** [tmlee/time_difference#49]
I've been [searching for](https://stackoverflow.com/q/59888418/673826) a way to calculate "humanized" but accurate time difference between time stamps way in the future. All approaches I tried thus far including this gem produce incorrect result.
```ruby
a = Time.parse('2044-11-18 01:00:00 -0600')
b = Time.parse('2045-03-05 04:00:00 -0600')
TimeDifference.between(a, b).humanize
```
produces `3 Months, 2 Weeks, 1 Day, 19 Hours, 32 Minutes and 42 Seconds`. There should not be minutes and seconds in the output I presume.

**Comment by mlt** [comment]
Apparently, it is a [Year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem)

**Comment by AlexWayfer** [comment]
> Apparently, it is a [Year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem)

Wow, good investigation!

**Comment by mlt** [comment]
Nevermind and I apologize for the noise. It is not Y2038 related. All is good as usually there are ~365.25 days in a year and month length calculated from there. It is all explained in a linked SO post.
